// SPDX-License-Identifier: LicenseRef-PolyForm-Internal-Use-1.0.0 OR LicenseRef-PolyForm-Noncommercial-1.0.0
/**
 * Long-lived notes, `orch mem` (new in v2): what a team of agents should still know next week.
 *
 * One Markdown file per entry, <dir>/<name>.md, with a frontmatter block:
 *   ---
 *   name: <name>
 *   description: <one line, shown in the index>
 *   type: <rule | lesson | fact | reference | note | any word>
 *   status: active | retired
 *   created_at: <iso>
 *   [superseded_by: <name>]  [retired_at: <iso>]  [retired_reason: <one line>]
 *   ---
 *   <body>
 * INDEX.md is generated from the files (one line per ACTIVE entry, oldest first) and is meant
 * to be read at the start of every session, so it has a line cap: at or over
 * [mem] index_max_lines, `add` still writes but warns. Retiring never deletes: the file stays,
 * marked retired with its successor, and drops out of the index.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync } from "node:fs";
import { withLock } from "./lock.js";
import { stamp } from "./mailbox.js";
import { atomicWrite, validName } from "./util.js";

export class MemError extends Error {
  constructor(msg: string) {
    super(msg);
    this.name = "MemError";
  }
}

export interface MemEntry {
  name: string;
  description: string;
  type: string;
  status: string;
  created_at: string;
  superseded_by?: string;
  retired_at?: string;
  retired_reason?: string;
  body: string;
  file: string;
}

const FIELD_ORDER = ["name", "description", "type", "status", "created_at", "superseded_by", "retired_at", "retired_reason"];
const INDEX = "INDEX.md";
const INDEX_HEAD = "# Index\n\nGenerated by `orch mem`; do not edit by hand. One line per active entry.\n\n";

function oneLine(v: string, what: string, max = 300): string {
  if (/[\r\n]/.test(v)) throw new MemError(`${what} must be one line`);
  const t = v.trim();
  if (!t) throw new MemError(`${what} is empty`);
  if (t.length > max) throw new MemError(`${what} is longer than ${max} characters`);
  return t;
}

export function checkName(name: string): string {
  if (!validName(name) || name.toUpperCase() === "INDEX" || name.endsWith(".md")) {
    throw new MemError(`bad name '${name}': use letters, digits, . @ _ - (not starting with ., not INDEX)`);
  }
  return name;
}

export function parseEntry(text: string, file: string): MemEntry | null {
  const m = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(text.replace(/\r\n/g, "\n"));
  if (!m) return null;
  const f: Record<string, string> = {};
  for (const line of m[1].split("\n")) {
    const i = line.indexOf(":");
    if (i > 0) f[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  if (!f.name || !f.description) return null;
  return {
    name: f.name, description: f.description, type: f.type || "note", status: f.status || "active",
    created_at: f.created_at || "", superseded_by: f.superseded_by, retired_at: f.retired_at,
    retired_reason: f.retired_reason, body: m[2].replace(/\n+$/, ""), file,
  };
}

function renderEntry(e: MemEntry): string {
  const lines = FIELD_ORDER.filter((k) => (e as any)[k] !== undefined && (e as any)[k] !== "").map((k) => `${k}: ${(e as any)[k]}`);
  return `---\n${lines.join("\n")}\n---\n${e.body ? e.body + "\n" : ""}`;
}

export interface AddResult {
  entry: MemEntry;
  indexLines: number;
  cap: number;
  warning: string | null;
}

export class Mem {
  readonly lock: string;
  constructor(readonly dir: string, readonly indexMaxLines = 200) {
    this.lock = `${dir}/.lock.d`;
  }

  file(name: string): string {
    return `${this.dir}/${checkName(name)}.md`;
  }

  all(): MemEntry[] {
    if (!existsSync(this.dir)) return [];
    const out: MemEntry[] = [];
    for (const f of readdirSync(this.dir).sort()) {
      if (!f.endsWith(".md") || f === INDEX || f.startsWith(".")) continue;
      const e = parseEntry(readFileSync(`${this.dir}/${f}`, "utf8"), `${this.dir}/${f}`);
      if (e && e.name === f.slice(0, -3)) out.push(e);
    }
    return out.sort((a, b) => (a.created_at < b.created_at ? -1 : a.created_at > b.created_at ? 1 : a.name < b.name ? -1 : 1));
  }

  get(name: string): MemEntry | undefined {
    const p = this.file(name);
    if (!existsSync(p)) return undefined;
    return parseEntry(readFileSync(p, "utf8"), p) ?? undefined;
  }

  /** Rewrite INDEX.md from the entry files; returns its entry-line count. */
  private reindex(): number {
    const active = this.all().filter((e) => e.status !== "retired");
    const lines = active.map((e) => `- [${e.name}](${e.name}.md) (${e.type}): ${e.description}`);
    atomicWrite(`${this.dir}/${INDEX}`, INDEX_HEAD + lines.join("\n") + (lines.length ? "\n" : ""));
    return lines.length;
  }

  private capWarning(n: number): string | null {
    return n >= this.indexMaxLines
      ? `index at cap: ${n}/${this.indexMaxLines} lines. Retire entries that are superseded, or merge related ones.`
      : null;
  }

  add(name: string, description: string, body: string, type = "note", now?: Date): AddResult {
    checkName(name);
    const desc = oneLine(description, "description");
    const ty = oneLine(type, "type", 40);
    if (!validName(ty)) throw new MemError(`bad type '${type}': one word`);
    mkdirSync(this.dir, { recursive: true });
    return withLock(this.lock, () => {
      const p = this.file(name);
      if (existsSync(p)) throw new MemError(`${name} exists: add a new entry and retire this one (orch mem retire ${name} --superseded-by NEW)`);
      const e: MemEntry = { name, description: desc, type: ty, status: "active", created_at: stamp(now), body: body.replace(/\s+$/, ""), file: p };
      atomicWrite(p, renderEntry(e));
      const n = this.reindex();
      return { entry: e, indexLines: n, cap: this.indexMaxLines, warning: this.capWarning(n) };
    });
  }

  retire(name: string, supersededBy?: string | null, reason?: string | null, now?: Date): MemEntry {
    checkName(name);
    if (!supersededBy && !reason) throw new MemError("retire needs --superseded-by NAME or --reason TEXT");
    if (supersededBy) checkName(supersededBy);
    if (supersededBy === name) throw new MemError("an entry cannot supersede itself");
    const why = reason ? oneLine(reason, "reason") : undefined;
    return withLock(this.lock, () => {
      const e = this.get(name);
      if (!e) throw new MemError(`no entry ${name}`);
      if (e.status === "retired") throw new MemError(`${name} is already retired${e.superseded_by ? ` (superseded by ${e.superseded_by})` : ""}`);
      if (supersededBy) {
        const s = this.get(supersededBy);
        if (!s) throw new MemError(`no entry ${supersededBy}: add the replacement first`);
        if (s.status === "retired") throw new MemError(`${supersededBy} is itself retired`);
      }
      Object.assign(e, { status: "retired", superseded_by: supersededBy ?? undefined, retired_at: stamp(now), retired_reason: why });
      atomicWrite(e.file, renderEntry(e));
      this.reindex();
      return e;
    });
  }

  /** Every term must appear (case-insensitive) in name, description, type or body. */
  search(terms: string[], opts: { type?: string | null; all?: boolean } = {}): MemEntry[] {
    const ts = terms.map((t) => t.toLowerCase()).filter((t) => t);
    return this.all().filter((e) => {
      if (!opts.all && e.status === "retired") return false;
      if (opts.type && e.type !== opts.type) return false;
      const hay = `${e.name}\n${e.description}\n${e.type}\n${e.body}`.toLowerCase();
      return ts.every((t) => hay.includes(t));
    });
  }

  indexLines(): number {
    try {
      return readFileSync(`${this.dir}/${INDEX}`, "utf8").split("\n").filter((l) => l.startsWith("- [")).length;
    } catch {
      return 0;
    }
  }
}
